### ISSUE TITLE
Can't select PD2HDChannelMap as an option when specifying tpc channel map

### ISSUE THREAD

**Issue by ShyamB97** [DUNE-DAQ/daqconf#125]
Need to add `PD2HDChannelMap` as an option for `--tpc-channel-map` in `daqconf_multiru_gen.py`.

**Comment by wesketchum** [comment]
@alessandrothea @ShyamB97 Is this moot now given the hardware map changes? I think so, so we can close?

**Comment by ShyamB97** [comment]
Yes I think so

**Comment by wesketchum** [comment]
Closing. We can reopen if needed then.
