### ISSUE TITLE
daqconf_multiru_gen -h produces 5048 lines of output, 98% diagnostic

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daqconf#197]
If I run `daqconf_multiru_gen -h`, over five thousand lines of output are created, with only the bottom 100 or so pertaining to the actual commands you can pass the script. It would be neater/more elegant if the user didn't see the first few thousand lines scroll by before seeing the actual help instructions.

**Comment by jcfreeman2** [comment]
Issue isn't specific to `daqconf_multiru_gen`; I see it with `nanorc` as well.

**Comment by plasorak** [comment]
https://github.com/brettviren/moo/pull/41 This is because we updated `moo` recently.
