### ISSUE TITLE
Typos in documentation and JSON

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daqconf#212]
I'm trying to play around with `daqconf` and running into typos in the documentation and JSON files. I feel like they should be carefully reviewed, since among other things I'm seeing:
* In the documentation, the `daqconf` example configuration script is still described as `daqconf/scripts/daqconf_full_config.json`, when on Thursday it was renamed as `daqconf/config/daqconf_full_config.json`
* In `daqconf/config/daqconf_full_config.json` itself, we have the line `"firmawre_hit_threshold": 20,` which causes errors when the configuration is used since there's a typo in "firmware"

Etc.?

**Comment by glehmannmiotto** [comment]
the errors in the daqconf_full_config are multiple and related to tags that don't exist anymore.
Besides the issue spotted by @jcfreeman2 and @ShyamB97 , also the dqm attributes are all wrong.

**Comment by eflumerf** [comment]
I updated daqconf_full_config in my linked PR, and ran `daqconf_multiru_gen` using it to make sure that there were no further errors.
