### ISSUE TITLE
daqconf not creating thread_pinning scripts/readout_affinity command in boot.json

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/daqconf#240]
Missing a way to create block like this
```
    "scripts": {
        "thread_pinning": {
            "cmd": [
                "readout-affinity.py --pinfile ${DUNEDAQ_THREAD_PIN_FILE}"
            ],
            "env": {
                "DUNEDAQ_THREAD_PIN_FILE": "/nfs/sw/dunedaq/dunedaq-v3.2.0-N22-10-28-dualapa/runarea/cpupin-node-optimal.json",
                "LD_LIBRARY_PATH": "getenv",
                "PATH": "getenv"
            }
        }
    }
```

needed for executing pin_threads before conf.

Needed for EHN1 integration week (so, should be based on patch/v3.2.x branches)

**Comment by plasorak** [comment]
Right now you can't use `~` or env variables for the thread pinning script path, you need to feed the path. Fixed here: https://github.com/DUNE-DAQ/daqconf/pull/241

**Comment by plasorak** [comment]
Closing this as this seems fixed
