### ISSUE TITLE
medium scale test failure

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/daqconf#268]
Medium scale test does not work as it sets weird values for host data (from the generated `boot.json`)
```
        "dfo": "np04-srv-018-100g",
        "hsi": "np04-srv-018-100g",
```
It might be that this is happening in other tests, but I haven't checked all of them, just stumble on this one.

**Comment by plasorak** [comment]
@glehmannmiotto @eflumerf do we expect this to work? My naïve solution here would be to add a switch to enable/disable data-network in the boot section of the schema/configuration... But there are at least two other solutions: we could remove these particular entries, so [these couple of lines](https://github.com/DUNE-DAQ/daqconf/blob/develop/scripts/daqconf_multiru_gen#L656-L661) or we could consider that this **must work** and make sure it does on the np04 cluster.

**Comment by glehmannmiotto** [comment]
This should actually work since the 100G and 10G network are connected in NP04. We may exclude this feature for now, but it should be reintroduced as soon as the sysadmins will have sorted out the routing.

**Comment by glehmannmiotto** [comment]
PS: affected hosts are np04-srv-018, 021 and 022

**Comment by plasorak** [comment]
This has been fixed by @JonathanHancock0
