### ISSUE TITLE
Reorganize daqconf schema options

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/daqconf#345]
The daqconf schema (https://github.com/DUNE-DAQ/daqconf/blob/develop/schema/daqconf/confgen.jsonnet) was originally split into groups in a fairly arbitrary way. The parameters should be reorganized to ensure that app-specific parameters are grouped together, and possibly add additional groups where needed for cross-app parameters (instead of putting most of them in `boot`).

**Comment by eflumerf** [comment]
I see this issue as a precursor to #330, as better organization will make those changes more straightforward

**Comment by alessandrothea** [comment]
PR #354 supersedes #330.
Related PRs
- `flxlibs`: DUNE-DAQ/flxlibs#120
- `wibmod`: DUNE-DAQ/wibmod#39
- `ctbmodules`: DUNE-DAQ/ctbmodules#20
- `timinglibs`: DUNE-DAQ/timinglibs#92
- `hermesmodules`: DUNE-DAQ/hermesmodules#5
- `daq-systemtest`: DUNE-DAQ/daq-systemtest#45
- `dfmodules`: DUNE-DAQ/dfmodules#297
- `integrationtest`: DUNE-DAQ/integrationtest#42

**Comment by plasorak** [comment]
I think we'll also need timinglibs, I can do that on Monday.
