### ISSUE TITLE
Network endpoints that require opening network ports must have the form `0.0.0.0:<port>` or equivalent

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/daqconf#45]
`daqconf` generated configurations (`init`) describe network connectivity without specifying whether each connection incoming or outgoing. This seems to pose a problem, as the application/iomanager/networkmanager infrastructure doesn't have the necessary information to tell whether the connection can be turned into the desired kind of endpoint.

```
    "connections": [
        {
            "data_type": "",
            "service_type": "kNetwork",
            "topics": [],
            "uid": "to_reverse",
            "uri": "tcp://{host_listrev_app_r}:12346"
        },
        {
            "data_type": "",
            "service_type": "kNetwork",
            "topics": [],
            "uid": "reversed",
            "uri": "tcp://{host_listrev_app_gv}:12347"
        }
    ],
```

Moreover,  connections that require the opening of a local port are expressed using the hostname. While this was suboptimal in the past, requiring nanorc performing Ip lookup (functionality now taken over by `ipm`), it stops working completely in Kubernetes in any case where PODs are hidden behind a workload: the workload and the POD have different IP addresses.
`daqconf` must be changed to replace the absolute hostname with `0.0.0.0` (or equivalent) for any connection (endpoint!) requiring opening a local port.

**Comment by eflumerf** [comment]
@alessandrothea does the changes in `iomanager` related to PR #51 meet the needs of this Issue?

**Comment by plasorak** [comment]
Oh good point I had forgotten about that

**Comment by roland-sipos** [comment]
So what is the verdict on this @plasorak ? Does that PR closes this?

**Comment by plasorak** [comment]
No, this needs to be another PR

**Comment by dingp** [comment]
Also related to PR #76

**Comment by plasorak** [comment]
Done
