### ISSUE TITLE
Topic and connection name

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/daqconf#57]
Code in here: https://github.com/DUNE-DAQ/networkmanager/blob/5094481e85b2212e3adf2839e3eaed6670fb533e/src/NetworkManager.cpp#L70 imply that the topic and the connetion name need to be different to not get a collision. Is this the expected behaviour? If so we should get `daqconf` to throw an error when this happens.

**Comment by eflumerf** [comment]
Yes, I believe that they need to be unique.

**Comment by plasorak** [comment]
Ok, just to be sure, I meant that if `topic==connection.uid` we get the error

**Comment by eflumerf** [comment]
Yes. Since those are both keys used to look up connections, they must be unique across all network connections.

EDIT: Of course, multiple connections can have the same topic.
